<?php
/**
 * @var \Bydn\VirtualMirror\Block\VirtualMirror $block
 */
?>
<div id="virtual-mirror-anchor" class="bydn-virtual-mirror">
    <button type="button" id="call-mirror-method" class="action primary tocart">
        <span>Try on me</span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#virtual-mirror-anchor": {
            "virtualMirrorProductAlert": {
                "buttonSelector": "#call-mirror-method",
                "generateImageEndpoint": "<?php echo $block->getUrl('virtualmirror/generateimage/index'); ?>"
            }
        }
    }
</script>
